# Generated by Django 4.0.4 on 2022-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=45)),
                ('long', models.CharField(max_length=45)),
                ('date_measure', models.CharField(max_length=45)),
                ('hour_measure', models.CharField(max_length=45)),
                ('gas_name', models.CharField(max_length=45)),
                ('gas_measure', models.CharField(max_length=45)),
                ('station_type', models.CharField(max_length=45)),
                ('origin_measure', models.CharField(max_length=45)),
            ],
        ),
    ]
